package com.dlq.dlqtest.model;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Date;

public class ClientLogin implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_client_login.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_client_login.createDate
     *
     * @mbggenerated
     */
    private Timestamp createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_client_login.clientId
     *
     * @mbggenerated
     */
    private Integer clientid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_client_login.cellphone
     *
     * @mbggenerated
     */
    private String cellphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_client_login.cellphoneType
     *
     * @mbggenerated
     */
    private String cellphonetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_client_login.invitationCode
     *
     * @mbggenerated
     */
    private String invitationcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_client_login.lastLoginTime
     *
     * @mbggenerated
     */
    private Date lastlogintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_client_login.comeFrom
     *
     * @mbggenerated
     */
    private String comefrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_client_login.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_client_login.freeze
     *
     * @mbggenerated
     */
    private Integer freeze;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_client_login.companyName
     *
     * @mbggenerated
     */
    private String companyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_client_login.staffName
     *
     * @mbggenerated
     */
    private String staffname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_client_login.companyAdd
     *
     * @mbggenerated
     */
    private String companyadd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_client_login.if_life
     *
     * @mbggenerated
     */
    private String ifLife;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_client_login.infoId
     *
     * @mbggenerated
     */
    private Integer infoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_client_login.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_client_login.headUrl
     *
     * @mbggenerated
     */
    private String headurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_client_login.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_client_login.infoId_original
     *
     * @mbggenerated
     */
    private Integer infoidOriginal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_client_login.sybOpenId
     *
     * @mbggenerated
     */
    private String sybopenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_client_login.openIdDate
     *
     * @mbggenerated
     */
   

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table td_client_login
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

	@Override
	public String toString() {
		return "ClientLogin [id=" + id + ", createdate=" + createdate + ", clientid=" + clientid + ", cellphone="
				+ cellphone + ", cellphonetype=" + cellphonetype + ", invitationcode=" + invitationcode
				+ ", lastlogintime=" + lastlogintime + ", comefrom=" + comefrom + ", password=" + password + ", freeze="
				+ freeze + ", companyname=" + companyname + ", staffname=" + staffname + ", companyadd=" + companyadd
				+ ", ifLife=" + ifLife + ", infoid=" + infoid + ", type=" + type + ", headurl=" + headurl + ", email="
				+ email + ", infoidOriginal=" + infoidOriginal + ", sybopenid=" + sybopenid + "]";
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Timestamp getCreatedate() {
		return createdate;
	}

	public void setCreatedate(Timestamp createdate) {
		this.createdate = createdate;
	}

	public Integer getClientid() {
		return clientid;
	}

	public void setClientid(Integer clientid) {
		this.clientid = clientid;
	}

	public String getCellphone() {
		return cellphone;
	}

	public void setCellphone(String cellphone) {
		this.cellphone = cellphone;
	}

	public String getCellphonetype() {
		return cellphonetype;
	}

	public void setCellphonetype(String cellphonetype) {
		this.cellphonetype = cellphonetype;
	}

	public String getInvitationcode() {
		return invitationcode;
	}

	public void setInvitationcode(String invitationcode) {
		this.invitationcode = invitationcode;
	}

	public Date getLastlogintime() {
		return lastlogintime;
	}

	public void setLastlogintime(Date lastlogintime) {
		this.lastlogintime = lastlogintime;
	}

	public String getComefrom() {
		return comefrom;
	}

	public void setComefrom(String comefrom) {
		this.comefrom = comefrom;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Integer getFreeze() {
		return freeze;
	}

	public void setFreeze(Integer freeze) {
		this.freeze = freeze;
	}

	public String getCompanyname() {
		return companyname;
	}

	public void setCompanyname(String companyname) {
		this.companyname = companyname;
	}

	public String getStaffname() {
		return staffname;
	}

	public void setStaffname(String staffname) {
		this.staffname = staffname;
	}

	public String getCompanyadd() {
		return companyadd;
	}

	public void setCompanyadd(String companyadd) {
		this.companyadd = companyadd;
	}

	public String getIfLife() {
		return ifLife;
	}

	public void setIfLife(String ifLife) {
		this.ifLife = ifLife;
	}

	public Integer getInfoid() {
		return infoid;
	}

	public void setInfoid(Integer infoid) {
		this.infoid = infoid;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getHeadurl() {
		return headurl;
	}

	public void setHeadurl(String headurl) {
		this.headurl = headurl;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Integer getInfoidOriginal() {
		return infoidOriginal;
	}

	public void setInfoidOriginal(Integer infoidOriginal) {
		this.infoidOriginal = infoidOriginal;
	}

	public String getSybopenid() {
		return sybopenid;
	}

	public void setSybopenid(String sybopenid) {
		this.sybopenid = sybopenid;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public ClientLogin() {
		super();
	}
    

}